export const UPDATE_TODO_TEXT = 'UPDATE_TODO_TEXT';
export const ADD_TODO = 'ADD_TODO';
export const CLEAR_INPUT_TODO_TEXT = 'CLEAR_INPUT_TODO_TEXT';
export const TOGGLE_CHECKBOX = 'TOGGLE_CHECKBOX';
export const DELETE_TODO = 'DELETE_TODO';